添加外国手机号登录功能
Darock-Studio/Darock-Bili pull request #374
Opened 2024-07-15 21:57 UTC by Linecom-lik

默认情况下，在TextField输入的1国家代码会自动作为美国，加拿大需要在列表中选择。

2024-07-15 21:59 UTC, Linecom-lik commented
!Run check

2024-07-15 22:03 UTC, Linecom-lik commented
!Run check

2024-07-15 22:11 UTC, Linecom-lik commented
!Run check

2024-07-16 05:36 UTC, WindowsMEMZ requested changes

2024-07-16 05:36 UTC, WindowsMEMZ commented on MeowBili/Others/LoginView.swift
> +                                    Text("").tag("")
无需使用空字符串占位，默认+86即可

2024-07-16 05:36 UTC, WindowsMEMZ commented on MeowBili/Others/LoginView.swift
> +                                    Text("").tag("")
同149行

2024-07-16 05:36 UTC, WindowsMEMZ commented on MeowBili/Others/PhoneFormatterExt.swift
> +func PhoneFormatter(region: String) -> String {
`40`行方法命名为小写字母开头，与此处不统一，将此处方法名改为`phoneFormatter`

2024-07-16 09:08 UTC, WindowsMEMZ approved these changes

2024-07-16 09:08 UTC, merged