尝试实现watchOS声音外放及其开关
Darock-Studio/Darock-Bili pull request #401
Opened 2024-08-27 11:54 UTC by FengzihangCode

在SettingsView增加了ExternalSound，在VideoPlayerView增加了相应播放类型控制
由于缺少Developer ID因此没有在本地运行测试，麻烦跑一下Actions

2024-08-27 12:48 UTC, FengzihangCode commented on MeowBili/Video/VideoPlayerView.swift
> +                    if externalSound {
变量名称统一为了externalSound

2024-08-27 12:50 UTC, FengzihangCode commented
修改了
My fault
这里的修改应该是在watchOS端进行的，所以说不是#if !os(watchOS)而是#if os(watchOS)
现在应该实现了

2024-08-27 12:52 UTC, WindowsMEMZ submitted a review, later dismissed

2024-08-27 12:52 UTC, WindowsMEMZ commented
!Run check

2024-08-27 12:56 UTC, FengzihangCode commented
CI 配置中的 Xcode 设置似乎有问题

Run sudo xcode-select -s /Applications/Xcode_16_beta_5.app
xcode-select: error: invalid developer directory '/Applications/Xcode_16_beta_5.app'
Error: Process completed with exit code 1.

2024-08-27 12:58 UTC, WindowsMEMZ commented
> CI 配置中的 Xcode 设置似乎有问题
> 
> Run sudo xcode-select -s /Applications/Xcode_16_beta_5.app xcode-select: error: invalid developer directory '/Applications/Xcode_16_beta_5.app' Error: Process completed with exit code 1.

容器更新了，稍等我更新配置

2024-08-27 13:00 UTC, WindowsMEMZ commented
!Run check

2024-08-28 02:06 UTC, FengzihangCode commented
CI验证的时候Error Code 65，怀疑是签名问题，但我这边应该无法处理这些问题

ChatGPT给出的解释如下：
从你提供的日志来看，GitHub Actions 中的 Error Code 65 与 Xcode 构建失败有关。日志中提到了一些重要的信息，可以帮助我们定位问题：
禁用预览：日志中多次提到由于 Swift 版本和优化级别设置的原因，禁用了 SwiftUI 预览功能。虽然这本身并不会导致构建失败，但它可能表明在你的项目配置中存在不一致的优化设置。
代码签名问题：日志中有警告信息指出，“MeowBili”和“MeowBili Watch App”目标没有进行代码签名，但需要启用相应的权限（entitlements）。如果你的项目需要某些权限，比如推送通知、iCloud、健康数据等，而这些目标未进行代码签名，这可能会导致构建失败。
运行脚本的配置：日志还提到运行脚本阶段“Run SwiftLint”和“Run Script”在每次构建时都会执行，因为这些阶段未启用“基于依赖分析”（Based on dependency analysis）的选项。这意味着每次构建都会执行这些脚本，可能会影响构建时间和性能，但通常不会导致构建失败。
解决方案
检查代码签名设置：确保项目中的所有目标都正确配置了代码签名。你可以在 Xcode 的“Signing & Capabilities”部分检查每个目标的签名设置。确保你有正确的开发者证书和描述文件。
调整优化设置：如果你不需要生产级别的优化设置，可以考虑在开发构建配置中将 SWIFT_OPTIMIZATION_LEVEL 设置为 -Onone。这有助于避免预览功能被禁用，同时可能避免其他构建问题。
查看权限配置：如果你的项目中使用了某些需要启用权限的功能（例如推送通知、iCloud），确保这些目标都已正确配置了 entitlements 文件，并且已进行代码签名。
本地验证：在本地尝试执行相同的构建命令，看看是否能复现相同的错误。如果能复现，使用 Xcode 的问题导航器或命令行构建工具 (xcodebuild) 查看更详细的错误信息。
确保所有依赖项正常配置：检查 CocoaPods、Carthage 或 Swift Package Manager 等工具的配置是否正确。确保它们已成功集成到项目中，且不会因为某些库的优化级别冲突导致构建失败。

2024-08-28 08:00 UTC, FengzihangCode commented
估计是SwiftUI的问题，现在把@AppStorage声明全部统一为了Bool后false，因为之前也声明了，但是就是没有识别到

2024-08-28 08:24 UTC, WindowsMEMZ requested changes

2024-08-28 08:24 UTC, WindowsMEMZ commented on MeowBili/Others/SettingsView.swift
> +    @AppStorage("externalSound") var externalSound: Bool = false
问题不在这，你的`Toggle`声明在`PlayerSettingsView`里，和变量声明不在一个结构体，当然用不了，更改声明位置。

2024-08-28 09:20 UTC, FengzihangCode commented on MeowBili/Others/SettingsView.swift
> +    @AppStorage("externalSound") var externalSound: Bool = false
已经移动到了PlayerSettingsView

2024-08-28 09:21 UTC, FengzihangCode commented
现在提交的版本解决了

2024-08-28 09:34 UTC, WindowsMEMZ approved these changes

2024-08-28 09:34 UTC, WindowsMEMZ commented
!Run check

2024-08-28 10:35 UTC, FengzihangCode commented
CI通过 现在应该解决了

2024-08-28 10:57 UTC, merged