完善英语翻译
Darock-Studio/Darock-Bili pull request #404
Opened 2024-09-02 04:20 UTC by FengzihangCode

把Localizable.xcstrings的英文翻译得差不多了，但是没有在Localizable里面的字符没有翻译

2024-09-02 13:17 UTC, FengzihangCode commented
!Run check

2024-09-03 13:48 UTC, Linecom-lik requested changes
## 翻译改进
* 中国大陆译为“China”
* 中国香港译为“China Hong Kong”
* 中国澳门译为“China Macao”
* 中国台湾应为“China Taiwan”（考虑政治因素）
* 英国建议译为“U.K.”或者“England”或者“Britain”（Watch屏幕空间因素）
* App版本应译为“App Version”
* 与此反馈重复应译为“Duplicate with this Feedback”
* 了解反馈状态译为“Learn More about Feedback Status”
* 换行建议“Enter”即可（方便理解）
* 未完成的编辑：Draft

### 一点注意
机翻味道很浓，不建议使用机翻。

2024-09-03 13:50 UTC, Linecom-lik submitted a review, later dismissed
## 翻译改进
* 中国大陆译为“China”
* 中国香港译为“China Hong Kong”
* 中国澳门译为“China Macao”
* 中国台湾应为“China Taiwan”（考虑政治因素）
* 英国建议译为“U.K.”或者“England”或者“Britain”（Watch屏幕空间因素）
* App版本应译为“App Version”
* 与此反馈重复应译为“Duplicate with this Feedback”
* 了解反馈状态译为“Learn More about Feedback Status”
* 换行建议“Enter”即可（方便理解）
* 未完成的编辑：Draft

### 一点注意
机翻味道很浓，不建议使用机翻。

2024-09-04 03:44 UTC, FengzihangCode commented
翻译的时候主要考虑的字符顺序英国那里是G因此翻译为了GB，因此同理也将United States更改为了America（不过这样字母顺序会乱

没使用机翻但是后面使用了Grammarly（可能会让内容有点生硬？主要是为了改正语法错误QAQ）
duplicate是名词因此Duplicate with this Feedback有问题（但他真的是名词，Grammarly帮我改的

综上，更改1-6与8-10

真的像机翻嘛QAQ我觉得我没有机翻那种逐字逐句字字落实的感觉啊（

2024-09-04 03:50 UTC, FengzihangCode commented
感觉HK和Macau前面加了China后好像又不太符合翻译惯例了

2024-09-04 03:50 UTC, FengzihangCode commented
!Run check

2024-09-04 04:04 UTC, Linecom-lik commented
duplicate 的名词是duplication GB是根据习惯来的、且国家并没有按照字母排序，保持US即可。发送自澪的Apple Watch Series 8在 2024年9月4日，11:44，DannyFeng ***@***.***> 写道：
翻译的时候主要考虑的字符顺序英国那里是G因此翻译为了GB，因此同理也将United States更改为了America（不过这样字母顺序会乱
没使用机翻但是后面使用了Grammarly（可能会让内容有点生硬？主要是为了改正语法错误QAQ）
duplicate是名词因此Duplicate with this Feedback有问题（但他真的是名词，Grammarly帮我改的
综上，更改1-6与8-10
真的像机翻嘛QAQ我觉得我没有机翻那种逐字逐句字字落实的感觉啊（

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

2024-09-04 04:05 UTC, Linecom-lik commented
政治因素发送自澪的Apple Watch Series 8在 2024年9月4日，11:51，DannyFeng ***@***.***> 写道：
感觉HK和Macau前面加了China后好像又不太符合翻译惯例了

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

2024-09-04 04:14 UTC, FengzihangCode commented
Solved.
还有问题的话直接说就行了

2024-09-04 04:15 UTC, FengzihangCode commented
!Run check

2024-09-05 05:24 UTC, FengzihangCode commented
Troubleshoot.problem.internet.meaning中文也没有写含义所以直接没有翻译
FB%1$@%2$@那个FB是指Feedback嘛？我把它当作反馈来翻译了
“”这种Xcode中没有预览的符号直接复制粘贴

现在Localization.xcstrings以及翻译完了，剩下的看用不用得着在Text或者Toggle之类的里面嵌套NSLocalizedString来翻译

这个合并之后我应该要提交实现小组件的代码，所以麻烦快一点@WindowsMEMZ

2024-09-05 05:25 UTC, FengzihangCode commented
!Run check

2024-09-05 13:51 UTC, Linecom-lik commented
还有就是 现在他肯定看不到，周六他才回家

2024-09-06 04:16 UTC, ThreeManager785 commented
> ## 翻译改进
> * 中国大陆译为“China”
> * 中国香港译为“China Hong Kong”
> * 中国澳门译为“China Macao”
> * 中国台湾应为“China Taiwan”（考虑政治因素）
> * 英国建议译为“U.K.”或者“England”或者“Britain”（Watch屏幕空间因素）
> * App版本应译为“App Version”
> * 与此反馈重复应译为“Duplicate with this Feedback”
> * 了解反馈状态译为“Learn More about Feedback Status”
> * 换行建议“Enter”即可（方便理解）
> * 未完成的编辑：Draft
> 
> ### 一点注意
> 机翻味道很浓，不建议使用机翻。

China HK和China Taiwan这种东西太奇怪了
既然是「国家或【地区】」，就不需要再次强调他属于中国了，累赘

2024-09-06 04:19 UTC, ThreeManager785 commented
> > Troubleshoot.problem.internet.meaning中文也没有写含义所以直接没有翻译 FB%1$@%2$@那个FB是指Feedback嘛？我把它当作反馈来翻译了 “”这种Xcode中没有预览的符号直接复制粘贴
> > 现在Localization.xcstrings以及翻译完了，剩下的看用不用得着在Text或者Toggle之类的里面嵌套NSLocalizedString来翻译
> > 这个合并之后我应该要提交实现小组件的代码，所以麻烦快一点@WindowsMEMZ
> 
> 俗话说得好，有些东西是不用翻译的，翻译了还可能导致歧义。
> 
> 并且国际化这块一直是 @ThreeManager785 负责的，建议向他 Request a Review

你们这个国际化实在是太逆天了

- MEMZ不写键名，他不在乎
- Linecom写出来十二分奇怪的句子

我会帮助MEMZ做本地化，我对我翻的句子负责（他现在也不用我了倒）。

喵哩可维护性极差，我也没有兴趣做了。建议交给Cape自动化。

2024-09-06 08:07 UTC, FengzihangCode commented
再检查了一次
把这次发现的问题列出来

1. Darock will collect essential diagnosis infos(->info) in order to fix the issue. Information不可数（两处问题重复）
2. Error.network-troubleshoot  Recommend (+to) run (+the) Network Troubleshooting
3. Home.no-internet Cannot(->Failed to ) connect to(-to) (+the) Internet
4. Update.checking Checking for Update(s)... 且在英语界面中显示不完整，*改为Update Checking或Checking？ 
5. Gesture.double-tap.description ... open at system settings(->System Settings )->Accessibility
6. 文件保险箱的状态显示的是中文（但似乎没有很合适的解决方案）
7. Search.no-result No (+Matching) Results
8. 此反馈已关闭，若要重新进行反馈，请创建一个新的反馈 create a new feedback(->one).
9. 喵哩喵哩调试构建。 Build %@.xc_verd.%@ 翻译中有一个中文句号
10. navbar.my “我的”翻译为了Me，“My”可能会更合适

综上，我再提交一次，结合 @ThreeManager785 的建议
至于China Hong Kong S.A.R.，我还是参照国际翻译惯例采用Hong Kong

如果还有其他问题，也请一并提出

2024-09-06 08:09 UTC, FengzihangCode commented
!Run check

2024-09-06 16:37 UTC, ThreeManager785 commented
> > > ## 翻译改进
> > > 
> > > * 中国大陆译为“China”
> > > * 中国香港译为“China Hong Kong”
> > > * 中国澳门译为“China Macao”
> > > * 中国台湾应为“China Taiwan”（考虑政治因素）
> > > * 英国建议译为“U.K.”或者“England”或者“Britain”（Watch屏幕空间因素）
> > > * App版本应译为“App Version”
> > > * 与此反馈重复应译为“Duplicate with this Feedback”
> > > * 了解反馈状态译为“Learn More about Feedback Status”
> > > * 换行建议“Enter”即可（方便理解）
> > > * 未完成的编辑：Draft
> > > 
> > > ### 一点注意
> > > 机翻味道很浓，不建议使用机翻。
> > 
> > 
> > China HK和China Taiwan这种东西太奇怪了 既然是「国家或【地区】」，就不需要再次强调他属于中国了，累赘
> 
> 中文“中国香港特别行政区”我认为最合适的翻译是 China Hong Kong S.A.R.，省去S.A.R.是考虑到屏幕空间

私认为：一般来讲，人们说“中国”就够了，不会每次都说“中华人民共和国”。China比PRC全称简单明了多了。

同理，“香港”不需要“中国香港特别行政区”，你说香港大家就知道你在哪，Hong Kong，非常明了，也不会让人觉得政治立场有问题。

2024-09-06 17:18 UTC, ThreeManager785 commented
> 再检查了一次 把这次发现的问题列出来
> 
> 1. Darock will collect essential diagnosis infos(->info) in order to fix the issue. Information不可数（两处问题重复）
> 2. Error.network-troubleshoot  Recommend (+to) run (+the) Network Troubleshooting
> 3. Home.no-internet Cannot(->Failed to ) connect to(-to) (+the) Internet
> 4. Update.checking Checking for Update(s)... 且在英语界面中显示不完整，*改为Update Checking或Checking？
> 5. Gesture.double-tap.description ... open at system settings(->System Settings )->Accessibility
> 6. 文件保险箱的状态显示的是中文（但似乎没有很合适的解决方案）
> 7. Search.no-result No (+Matching) Results
> 8. 此反馈已关闭，若要重新进行反馈，请创建一个新的反馈 create a new feedback(->one).
> 9. 喵哩喵哩调试构建。 Build %@.xc_verd.%@ 翻译中有一个中文句号
> 10. navbar.my “我的”翻译为了Me，“My”可能会更合适
> 
> 综上，我再提交一次，结合 @ThreeManager785 的建议 至于China Hong Kong S.A.R.，我还是参照国际翻译惯例采用Hong Kong
> 
> 如果还有其他问题，也请一并提出

喵哩我真想fork一个爆改，但是写出来了也不好改了。现在这个真是太烂了。UI是分散不协的，本地化是烂得一批的，代码是混乱不堪的。

2024-09-07 00:22 UTC, FengzihangCode commented
其实我最先提交的PR就是为了能够在学校里面外放声音，但是当时改的时候基本上只能把所有路径展开来找代码，说真的第一次改的时候头都肿了QAQ，唯一能帮助我理解代码的就是参考下View的名称，然后看看一堆toggle的名称，再在自己的Watch App上面找到对应位置，幸好第一次改的是SettingsView，不然这波基本没看到注释算是无从下手了，所以我开学之前的话就打算先把代码理解，然后实现AppIntents和Widgets，这样可以先实现一个跨App用户体验，而且还有URL Scheme，这个功能实现过后就可以允许Siri的指令，而且可以让Widgets不再只是一个数据看板，至于优化重构，我可能时间不太够，因为马上就初三了，如果初三完了之后还在进行的话，我还是乐意效劳🥳


Sent from my Apple Watch

2024-09-07 00:49 UTC, FengzihangCode commented
刚才翻了下以前的Issue，如果要重构的话，不妨考虑一下以前放弃掉的那些好点子[https://github.com/Darock-Studio/Darock-Bili/issues/98#issuecomment-1922589208](url) @ThreeManager785

我觉得这个项目空间还很大，挺期待v3.0.0的（希望在Apple Watch 10周年之际带来大幅优化与改进）

2024-09-07 00:51 UTC, FengzihangCode commented
不过似乎聊偏题了，这个翻译的提交麻烦Merge或是Close @Linecom-lik

2024-09-07 04:58 UTC, Linecom-lik commented
> 不过似乎聊偏题了，这个翻译的提交麻烦Merge或是Close @Linecom-lik

我只能帮你close，merge需要 @WindowsMEMZ

2024-09-07 04:59 UTC, Linecom-lik commented
今天晚上他会来Review

2024-09-07 05:30 UTC, FengzihangCode commented
> 今天晚上他会来Review

Okay，不过MEMZ周六还没放？

2024-09-07 07:06 UTC, ThreeManager785 commented
> > 不过似乎聊偏题了，这个翻译的提交麻烦Merge或是Close @Linecom-lik
> 
> 我只能帮你close，merge需要 @WindowsMEMZ

我能Merge

2024-09-07 07:07 UTC, ThreeManager785 commented
> > 今天晚上他会来Review
> 
> Okay，不过MEMZ周六还没放？

MEMZ学校周六上课

我能Merge

2024-09-07 07:31 UTC, FengzihangCode commented
那要不等MEMZ吧，毕竟他今天就可以检查，我觉得翻译多一个人检查会更好（反正也不着急😊正好给小组件再优化一下  ***@***.***


Sent from my Apple Watch

2024-09-07 07:39 UTC, FengzihangCode commented
还有，我想到File Vault状态显示中文的解决方案了，可以用之前提及过的NSLocalizedString套在已停用和已启用的文字上，这样就解决了


Sent from my Apple Watch

2024-09-07 09:06 UTC, WindowsMEMZ approved these changes

2024-09-07 09:07 UTC, merged