初步实现Widgets
Darock-Studio/Darock-Bili pull request #409
Opened 2024-09-08 13:50 UTC by FengzihangCode

AppIntents与URL Scheme都没有实现，只有Widgets的视频标题

因为明天开学（

实在对不起（

2024-09-08 13:52 UTC, FengzihangCode commented
有冲突（

代码能够运行，这几天应该没法改了（（（

对不起（（（（（

2024-09-15 01:06 UTC, WindowsMEMZ commented
在完成功能实现前，将 Pull Request 转为草稿。

2024-09-15 02:04 UTC, FengzihangCode commented
我的意思是Widgets已经作为一个数据看板的方式实现了，即使URL Scheme和App Intents还没有实现，也不影响这个功能的运行。URL Scheme和App Intents都是用于扩展Widgets的功能的，主要是支持Siri和通过Widgets打开对应页面或视频，对于之前提交的文件冲突，我很快会提交解决冲突后的代码，在此之前，也请检查一下代码，提供一点意见，我应该会把上个提交之后的Localizable翻译且解决文件冲突后提交这个版本，App Intents和URL Scheme由于时间问题我没法一次性提交，而且这两个功能肯定要多次调试，因此这个PR不会包括上述两个功能，我会尽可能逐步实现并提交


Sent from my Apple Watch

2024-09-15 02:34 UTC, WindowsMEMZ requested changes

2024-09-15 02:34 UTC, WindowsMEMZ commented on DarockBili.xcodeproj/project.pbxproj
> +				MARKETING_VERSION = 1.0;
版本号更改为`1.0.0`，第 2057, 2089 行也一并更改。

2024-09-15 02:34 UTC, WindowsMEMZ commented on DarockBili.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 17.2;
iOS 构建目标版本应该为 `17.0`，第 2051, 2083 行一并更改。

2024-09-15 02:34 UTC, WindowsMEMZ commented on MeowBili/Others/BiliBiliAPIService.swift
此文件供 Widget 使用，应当移动到 `MeowWidget` 文件夹下，同时从 `MeowBili` 和 `MeowBili Watch App` 两个 Target 中移除，仅包含在 `MeowWidgetExtension` Target 中。

2024-09-15 02:34 UTC, WindowsMEMZ commented on MeowWidget/MeowWidget.swift
> +        .supportedFamilies([.systemSmall, .systemMedium, .systemLarge, .accessoryCircular, .accessoryRectangular])
构建错误，
```
'systemSmall' is unavailable in watchOS
'systemMedium' is unavailable in watchOS
'systemLarge' is unavailable in watchOS
```

2024-09-15 02:44 UTC, FengzihangCode commented
好的，上面三条在解决冲突后会直接解决，下面的用if !os（我还以为watchOS会直接区分掉iOS小组件样式


Sent from my Apple Watch

2024-09-15 02:48 UTC, FengzihangCode commented
等我做完作业就解决（还有，BiliBiliAPIService在后面实现App Intents之类的功能的时候可能会需要，麻烦再确认一下是不是以后只有Widgets会使用


Sent from my Apple Watch

2024-09-15 02:52 UTC, WindowsMEMZ commented on MeowBili/Others/BiliBiliAPIService.swift
> 还有，BiliBiliAPIService在后面实现App Intents之类的功能的时候可能会需要，麻烦再确认一下是不是以后只有Widgets会使用

如果要在 Target 之间共享代码，请在**项目根目录**下创建`SharedCode`文件夹，并将此文件移动到新文件夹中。

2024-09-15 02:54 UTC, FengzihangCode commented
知道了，谢谢。


Sent from my Apple Watch

2024-09-17 03:49 UTC, closed without merging

2024-09-17 03:50 UTC, FengzihangCode commented
我先Closed了 直接解决冲突重新写

2024-09-17 03:56 UTC, FengzihangCode commented
我估计会过一阵子才能继续PR 最近学校事情太多了