MeowWidget错误修复与优化
Darock-Studio/Darock-Bili pull request #426
Opened 2024-10-25 14:11 UTC by FengzihangCode

本提交是完善MeowWidget的，对部分代码进行了修改，添加了MeowWidgetWatch

记得原本target可以同时设置iOS与watchOS的，今天发现不行，因此只能单独为iOS与watchOS创建了两个target

如果可以在一个target中解决这些问题，麻烦给我说一声

修复：
·Widget还不支持watchOS
·iOS端Widget没有显示App图标
·小Widget内容显示不全
·深色模式下小组件背景颜色不和谐
·小组件作者与播放量不可用
·为MeowWidget预览页面提供真实数据

#425

2024-10-25 14:11 UTC, FengzihangCode commented
!Run check

2024-10-26 09:19 UTC, WindowsMEMZ requested changes
即使 iOS 和 watchOS 分为两个 Target，也最好共享相同的代码，而不是为两个平台分别复制一份。

2024-10-26 09:29 UTC, FengzihangCode commented
> 即使 iOS 和 watchOS 分为两个 Target，也最好共享相同的代码，而不是为两个平台分别复制一份。

两个target 一份代码共用？

2024-10-26 09:32 UTC, WindowsMEMZ commented
> > 即使 iOS 和 watchOS 分为两个 Target，也最好共享相同的代码，而不是为两个平台分别复制一份。
> 
> 两个target 一份代码共用？

![image](https://github.com/user-attachments/assets/5ca8d9b9-1253-4203-98bb-ce071a3b8cdc)

在 `Target Membership` 中将代码文件同时添加到两个 Target 中。

2024-10-26 09:35 UTC, FengzihangCode commented
> > > 即使 iOS 和 watchOS 分为两个 Target，也最好共享相同的代码，而不是为两个平台分别复制一份。
> 
> > 
> 
> > 两个target 一份代码共用？
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/5ca8d9b9-1253-4203-98bb-ce071a3b8cdc)
> 
> 
> 
> 在 `Target Membership` 中将代码文件同时添加到两个 Target 中。

了解了 回家处理

2024-10-26 14:00 UTC, WindowsMEMZ submitted a review, later dismissed

2024-10-26 14:01 UTC, WindowsMEMZ commented
!Run check

2024-10-26 14:19 UTC, WindowsMEMZ commented
@FengzihangCode 需要解决的问题：

```
error: Build input file cannot be found: '/Users/runner/work/Darock-Bili/Darock-Bili/MeowWidgetWatch/Info.plist'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it? (in target 'MeowWidgetWatchExtension' from project 'DarockBili')
```

2024-10-26 14:22 UTC, FengzihangCode commented
> @FengzihangCode 需要解决的问题：
> 
> ```
> error: Build input file cannot be found: '/Users/runner/work/Darock-Bili/Darock-Bili/MeowWidgetWatch/Info.plist'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it? (in target 'MeowWidgetWatchExtension' from project 'DarockBili')
> ```

看起来似乎是因为没有完全清理MeowWidgetWatch的残留 我处理一下

2024-10-26 14:47 UTC, FengzihangCode commented
!Run check

2024-10-26 14:48 UTC, WindowsMEMZ approved these changes

2024-10-26 15:17 UTC, WindowsMEMZ commented
@FengzihangCode 需要解决的问题：

```
/Users/runner/work/Darock-Bili/Darock-Bili/MeowWidget/MeowWidgetBundle.swift:22:1: error: 'main' attribute can only apply to one type in a module
@main
^
/Users/runner/work/Darock-Bili/Darock-Bili/MeowBili/MeowBiliApp.swift:118:1: error: 'main' attribute can only apply to one type in a module
@main
^
```

2024-10-26 15:20 UTC, FengzihangCode commented
还是有问题（
我打算直接回到现在的正式版本 在这个基础上重新改

2024-10-26 15:22 UTC, WindowsMEMZ commented
你其实应该先在本地看看能不能编译再push上来的

2024-10-26 15:45 UTC, closed without merging

2024-10-26 16:08 UTC, FengzihangCode commented
> 你其实应该先在本地看看能不能编译再push上来的

道理都懂 设备受限
现在用的这台机子现在还在跑Ventura 无法编译这个项目
代码基本是靠Xcode检查+人+CI完成的

2024-10-26 16:10 UTC, FengzihangCode commented
> > 你其实应该先在本地看看能不能编译再push上来的
> 
> 道理都懂 设备受限 现在用的这台机子现在还在跑Ventura 无法编译这个项目 代码基本是靠Xcode检查+人+CI完成确认的

不然我也不可能提交出这种乱七八糟的问题了（