MeowWidget错误修复与优化 第二次提交
Darock-Studio/Darock-Bili pull request #427
Opened 2024-10-26 15:48 UTC by FengzihangCode

修复：
·Widget还不支持watchOS
·iOS端Widget没有显示App图标
·小Widget内容显示不全
·深色模式下小组件背景颜色不和谐
·小组件作者与播放量不可用
·为MeowWidget预览页面提供真实数据

#425 #426

2024-10-26 15:49 UTC, FengzihangCode commented
!Run check

2024-10-26 15:55 UTC, FengzihangCode commented
!Run check

2024-10-26 16:30 UTC, WindowsMEMZ requested changes

2024-10-26 16:30 UTC, WindowsMEMZ commented on DarockBili.xcodeproj/project.pbxproj
> +				B230F2E92CCD47FF00DB5A3A /* MeowWidgetBundle.swift in Sources */,
根据 CI 来看，明显 Target 选错了。本行、`1314` 行以及 `1384` 行似乎显示小组件文件被添加到了主 App Target 中。

应仅添加到 Widget Target 中。

2024-10-27 00:02 UTC, FengzihangCode commented
现在应该可以了（
我觉得我人要崩溃了（（

2024-10-27 00:03 UTC, FengzihangCode commented
!Run check

2024-10-27 00:09 UTC, FengzihangCode commented
!Run check

2024-10-27 00:25 UTC, FengzihangCode commented
现在应该完全解决问题了

2024-10-27 03:46 UTC, WindowsMEMZ approved these changes

2024-10-27 03:47 UTC, merged